title: "The Guestbook — TryHackMe CTF"
description: "Professional portfolio documentation for The Guestbook TryHackMe room."
theme: jekyll-theme-hacker
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
sass:
  style: compressed
include:
  - docs
